# site settings
title: "JIANRU"
subtitle: 
email: dengjr@student.ubc.ca
description: A Data Science Learner interested in Maching Learning, and Data Visualization
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Jianru
street_address: 
city: Vancouver
state: BC
zip_code: 
country: Canada
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jianructose
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
